version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      lit:
        patterns:
          - "lit"
          - "lit-*"
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "vite-*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      types:
        patterns:
          - "@types/*"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
